window.RECEPTION_DEMO_DATA = {
  persona: {
    name: "Mia Chen",
    role: "Senior Field Marketing Manager",
    company: "Sprig",
    city: "San Francisco",
    eventVolume: "46 dinners per year",
  },
  stages: [
    "Portfolio",
    "Connect",
    "Brief",
    "Source",
    "Approve",
    "Coordinate",
    "Book",
    "Invite",
    "Run",
    "Report",
    "Trust",
  ],
  portfolioMetrics: [
    ["May events", "10"],
    ["Active pipeline", "$6.8M"],
    ["Projected spend", "$43.7K"],
    ["Open decisions", "7"],
    ["At-risk SLAs", "2"],
  ],
  monthlyEvents: [
    {
      id: "acme",
      date: "May 14",
      time: "6:30 PM",
      account: "Acme Corp",
      title: "Expansion team dinner",
      city: "San Francisco",
      type: "Private dining",
      owner: "Mia Chen",
      status: "Needs approval",
      health: "Attention",
      nextAction: "Approve Merchant Room hold",
      sla: "2h 14m",
      guests: "14",
      budget: "$3.4K",
      pipeline: "$740K",
    },
    {
      id: "northstar",
      date: "May 16",
      time: "7:00 PM",
      account: "Northstar Bank",
      title: "CFO roundtable",
      city: "New York",
      type: "Executive dinner",
      owner: "Lena Ortiz",
      status: "Sourcing",
      health: "On track",
      nextAction: "Review 5 venue matches",
      sla: "18h",
      guests: "18",
      budget: "$5.8K",
      pipeline: "$1.2M",
    },
    {
      id: "helio",
      date: "May 17",
      time: "5:30 PM",
      account: "HelioWorks",
      title: "Conference sponsor dinner",
      city: "Austin",
      type: "Conference dinner",
      owner: "Mia Chen",
      status: "Vendor replies",
      health: "On track",
      nextAction: "Compare deposit terms",
      sla: "9h",
      guests: "22",
      budget: "$7.1K",
      pipeline: "$980K",
    },
    {
      id: "waypoint",
      date: "May 18",
      time: "12:30 PM",
      account: "Waypoint AI",
      title: "Customer advisory lunch",
      city: "San Francisco",
      type: "Lunch",
      owner: "Nora Patel",
      status: "Invites live",
      health: "On track",
      nextAction: "Collect 3 dietary forms",
      sla: "1d",
      guests: "12",
      budget: "$2.6K",
      pipeline: "$420K",
    },
    {
      id: "meridian",
      date: "May 20",
      time: "6:00 PM",
      account: "Meridian Health",
      title: "Renewal dinner",
      city: "Chicago",
      type: "Private dining",
      owner: "Lena Ortiz",
      status: "Booked",
      health: "On track",
      nextAction: "Send attendee packet",
      sla: "2d",
      guests: "16",
      budget: "$4.9K",
      pipeline: "$860K",
    },
    {
      id: "kestrel",
      date: "May 21",
      time: "6:45 PM",
      account: "Kestrel Bio",
      title: "Prospect dinner",
      city: "Boston",
      type: "Private dining",
      owner: "Mia Chen",
      status: "SLA risk",
      health: "At risk",
      nextAction: "Escalate no-reply venue",
      sla: "46m",
      guests: "10",
      budget: "$3.1K",
      pipeline: "$510K",
    },
    {
      id: "atlas",
      date: "May 23",
      time: "3:00 PM",
      account: "Atlas Retail",
      title: "Regional off-site",
      city: "Seattle",
      type: "Off-site",
      owner: "Nora Patel",
      status: "Planning",
      health: "On track",
      nextAction: "Confirm AV requirements",
      sla: "3d",
      guests: "35",
      budget: "$9.2K",
      pipeline: "$1.1M",
    },
    {
      id: "lattice",
      date: "May 24",
      time: "7:30 PM",
      account: "LatticeWorks",
      title: "Partner dinner",
      city: "Los Angeles",
      type: "Partner dinner",
      owner: "Mia Chen",
      status: "Needs approval",
      health: "Attention",
      nextAction: "Approve outreach drafts",
      sla: "4h",
      guests: "20",
      budget: "$5.4K",
      pipeline: "$690K",
    },
    {
      id: "orbital",
      date: "May 27",
      time: "6:00 PM",
      account: "Orbital Cloud",
      title: "Champion dinner",
      city: "Denver",
      type: "Private dining",
      owner: "Lena Ortiz",
      status: "Booked",
      health: "On track",
      nextAction: "Day-of comms queued",
      sla: "5d",
      guests: "13",
      budget: "$3.7K",
      pipeline: "$350K",
    },
    {
      id: "clearbit",
      date: "May 29",
      time: "8:00 AM",
      account: "Clearbit Labs",
      title: "Executive breakfast",
      city: "New York",
      type: "Breakfast",
      owner: "Nora Patel",
      status: "Sourcing",
      health: "At risk",
      nextAction: "Find private room under budget",
      sla: "1h 20m",
      guests: "9",
      budget: "$2.5K",
      pipeline: "$260K",
    },
  ],
  portfolioLanes: [
    ["Sourcing", "2 events", "7 venues to review"],
    ["Negotiating", "2 events", "4 vendor replies parsed"],
    ["Approval", "2 events", "3 human gates waiting"],
    ["Booked", "3 events", "41 attendees in coordination"],
    ["Day-of", "1 event", "Slack and email alerts queued"],
  ],
  connectors: [
    {
      name: "Gmail",
      access: "Read broad, send by approval",
      status: "Connected",
      signal: "17 prior venue threads found",
    },
    {
      name: "Google Calendar",
      access: "Availability and holds",
      status: "Connected",
      signal: "Exec team conflicts cleared",
    },
    {
      name: "HubSpot",
      access: "Accounts, opportunities, outcomes",
      status: "Connected",
      signal: "$2.4M pipeline in target segment",
    },
    {
      name: "Slack",
      access: "Owner notifications",
      status: "Connected",
      signal: "#field-events ready for day-of alerts",
    },
  ],
  briefText:
    "Book a 14-person dinner in SoMa next Thursday for the Acme expansion team. Italian or steakhouse, private room preferred, about $200 per person. Invite the AE, SE, and customer champions. Make it feel polished but not stuffy.",
  extractedBrief: [
    ["Event type", "Client dinner"],
    ["Date", "Thursday, May 14, 2026"],
    ["Neighborhood", "SoMa, San Francisco"],
    ["Party size", "14 guests"],
    ["Cuisine", "Italian or steakhouse"],
    ["Budget", "$200 per person"],
    ["Preference", "Private room, polished, not stuffy"],
    ["CRM account", "Acme Corp expansion"],
  ],
  learningSignals: [
    "Sprig hosted 18 private dinners in the last 9 months",
    "Italian venues convert 22 percent better for this segment",
    "Sales prefers walkable venues within 12 minutes of Moscone",
    "Finance guardrail: deposits over 30 percent need VP approval",
  ],
  venues: [
    {
      id: "atelier",
      name: "Atelier Meridian",
      image: "assets/venue-atelier.jpg",
      cuisine: "Modern Italian",
      area: "Yerba Buena",
      score: 94,
      capacity: "Private room for 16",
      budget: "$185-$215 pp",
      min: "$2,500 F&B minimum",
      reply: "84 percent reply likelihood",
      status: "Recommended",
      reasons: [
        "Capacity confirmed for a 14-top",
        "Matches Sprig's prior Italian dinner wins",
        "Walkable from Acme's conference hotel",
      ],
    },
    {
      id: "merchant",
      name: "Merchant Room",
      image: "assets/venue-merchant.jpg",
      cuisine: "Steakhouse",
      area: "South Beach",
      score: 89,
      capacity: "Semi-private room for 18",
      budget: "$190-$230 pp",
      min: "$3,000 F&B minimum",
      reply: "72 percent reply likelihood",
      status: "Strong fit",
      reasons: [
        "Best fit for executive-heavy attendee mix",
        "Reliable day-of score from cross-customer signal",
        "Has a May 14 hold window in prior thread",
      ],
    },
    {
      id: "civic",
      name: "Civic Table",
      image: "assets/venue-civic.jpg",
      cuisine: "California seasonal",
      area: "SoMa",
      score: 82,
      capacity: "Chef table for 14",
      budget: "$165-$195 pp",
      min: "$2,200 F&B minimum",
      reply: "61 percent reply likelihood",
      status: "Backup",
      reasons: [
        "On-budget and highly walkable",
        "Dietary flexibility is strongest in shortlist",
        "Less aligned with requested cuisine",
      ],
    },
  ],
  outreach: [
    {
      venue: "Atelier Meridian",
      subject: "Private dining inquiry for Sprig x Acme, May 14",
      body:
        "Hi Julia, Sprig is planning a polished 14-person client dinner in SoMa on Thursday, May 14. We'd love to check availability for a private room, Italian-forward menu, and an all-in budget around $200 per guest. Could you share availability, F&B minimum, deposit terms, and menu options?",
    },
    {
      venue: "Merchant Room",
      subject: "May 14 client dinner hold for Sprig",
      body:
        "Hi Daniel, Sprig is hosting an Acme expansion-team dinner for 14 guests on Thursday, May 14. Your semi-private room looks like a strong fit. Could you confirm availability, minimums, deposit requirements, and whether you can support a few dietary needs?",
    },
  ],
  vendorReplies: [
    {
      venue: "Atelier Meridian",
      received: "18 minutes ago",
      parsed: {
        availability: "Available, 7:00 PM",
        minimum: "$2,800 F&B",
        deposit: "25 percent",
        cancellation: "72 hours",
      },
      sentiment: "Warm reply, menu attached",
      action: "Ready for final comparison",
    },
    {
      venue: "Merchant Room",
      received: "41 minutes ago",
      parsed: {
        availability: "Available, 6:30 PM",
        minimum: "$3,000 F&B",
        deposit: "20 percent",
        cancellation: "5 business days",
      },
      sentiment: "Strong fit, private host included",
      action: "Recommended winner",
    },
    {
      venue: "Civic Table",
      received: "No reply",
      parsed: {
        availability: "Pending",
        minimum: "Unknown",
        deposit: "Unknown",
        cancellation: "Unknown",
      },
      sentiment: "SLA follow-up draft queued",
      action: "Waitlist as backup",
    },
  ],
  attendees: [
    ["Mia Chen", "Owner", "Confirmed", "None"],
    ["Jordan Lee", "AE", "Confirmed", "Vegetarian"],
    ["Priya Shah", "SE", "Confirmed", "None"],
    ["Marco Ruiz", "CRO", "Confirmed", "Gluten-free"],
    ["Avery Brooks", "Acme VP Ops", "Confirmed", "Shellfish allergy"],
    ["Nina Park", "Acme Finance", "Awaiting", "Unknown"],
  ],
  timeline: [
    ["10:00 AM", "Agent confirms final headcount with Mia and syncs calendar hold"],
    ["1:15 PM", "Merchant Room asks for dietary list; agent sends approved summary"],
    ["4:30 PM", "Slack alert routes arrival notes to #field-events"],
    ["6:05 PM", "Host confirms table is ready and prints attendee place cards"],
    ["9:32 PM", "Agent opens post-event follow-up tasks for account team"],
  ],
  outcomes: [
    ["Event spend", "$3,360"],
    ["Opportunities influenced", "$740,000"],
    ["Attendee conversion", "8 of 11 target contacts engaged"],
    ["Coordination time saved", "9.5 hours"],
    ["Recommended next step", "AE follow-up within 24 hours"],
  ],
  auditTrail: [
    ["Planner", "Extracted brief into structured criteria", "Reversible"],
    ["Tool router", "Searched venue corpus and prior mailbox threads", "Logged"],
    ["Mia Chen", "Approved two outbound vendor emails", "Human gate"],
    ["Parser", "Converted vendor replies into booking fields", "Reversible"],
    ["Mia Chen", "Approved Merchant Room deposit hold", "Human gate"],
    ["CRM sync", "Attached event outcome to Acme expansion opportunity", "Logged"],
  ],
};
